### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by dariusc93** [fihgus/Slash#12]
I notice that you all replace vanilla classes with custom ones. Instead of doing that, why not replace/override the method with your own so you dont have a classpath of net/minecraft or its full classes. This could prevent conflicts and also makes it more manageable in development (and would be the proper way because no mod should have the classpath of net/minecraft unless you want conflicts with future versions of forge, those who are stuck on a older version of forge for any specific reason (modpack related possibly), etc). As for events, you could basically do the same thing when replacing the methods. Another suggestion would be to include your build.gradle file in your git repo to allow developers who want to fork, poke, push and submit a PR to have what you have when it comes to setting up the development environment, building, and distributing this mod (Some like to make their own private modifications for their own servers). I may add on but its just a few suggestions for future release and use of this mod.

**Comment by fihgus** [comment]
Base classes' methods are replaced with java reflection(when compiled, they are actually placed in a different path, you can read the Classtransformer.class for more info).
so it is only changing methods that I have in my replacement class, if another version of forge have a method that I do not know, it's untouched.

=======================================================

I will put the build.gradle file into the repo, thank thank you for giving me your advise.
