### ISSUE TITLE
Server startup issues

### ISSUE THREAD

**Issue by TheKodex** [fihgus/Slash#13]
1. When I log on first time after I have started the server, I'm getting the timeout error message (Internal exception: io.netty.handler.ReadTimeOutException) Then I try again, and then it works. But this happens everytime after I try login after I've started my server. This server is on the same computer as the client, so I log in as localhost.

2. It seems like the loading time of the server is heavily increased with this mod. (33 seconds with this mod, compared to 9 seconds, no mods at all)

**Comment by fihgus** [comment]
fix planned as following:

Remove unused entry from packag.srg to improve search time.
Force load modified classes to get server ready before players are able to login.

**Comment by fihgus** [comment]
fixed in version 0.82
