### ISSUE TITLE
Can add limit setting for each player? 

### ISSUE THREAD

**Issue by FtyBN** [fihgus/Slash#26]
最近使用了开发者的插件,感觉不错用
但在claim地方面,却发现玩家可以无限制地claim地 (claim地的數目和大小)
而且OP沒有權限管理玩家的土地
这在管理上做成了很大的难处,有方法可以完善这方面的缺憾吗?

**Comment by fihgus** [comment]
claim 命令是应该由 op 给代替player 使用， 然后再share 给player。
我有计划做个范围限制出来， 不过这个会排比较后面。
最后， 马上更新的 0.83 会有给个特殊权限出来， 允许特定玩家 unshare unclaim 其他人的土地。

**Comment by FtyBN** [comment]
明白了,期代你的更新

**Comment by fihgus** [comment]
现已加入肯德基全家桶...
