### ISSUE TITLE
About /warp teleport to other player

### ISSUE THREAD

**Issue by FtyBN** [fihgus/Slash#27]
使用 /warphere tp其他玩家时会有等待对方玩家接受的讯息 , 但使用/warp <玩家> 时,却不会有等待玩家的讯息出现,会直接传送到该玩家所在地

**Comment by fihgus** [comment]
okay， 这个是因为我懒来着。。。
回头有空就搞。

--- Original Message ---

**Comment by FtyBN** [comment]
辛苦你了 :)
