### ISSUE TITLE
Mixin integration

### ISSUE THREAD

**Issue by liach** [fihgus/Slash#32]
Mixin is a type of new injector developed by Mumfrey, which injects into classes. https://github.com/SpongePowered/Mixin

**Comment by fihgus** [comment]
Could you give me a brief of what this does and what's the advantage?

**Comment by liach** [comment]
Forgeessentials had already applied it. It integrates a dynamic injection system, different from Forge's injection. A mixin can be even injected by another mixin, which is called "supermixins". And absolutely forge doesn't behave like this. It can only inject once.

**Comment by liach** [comment]
Um... Sad story happened on forge...
