### ISSUE TITLE
有个小建议(关于Claim)

### ISSUE THREAD

**Issue by FtyBN** [fihgus/Slash#34]
最近想在主城整理數塊地給VIP用
但因為Claim地不能重疉,變成需要我把主城拆成12塊地才能夠做到我想要的效果
我看到開發者之前是把這個重疊Bug Fix了,但這個Bug從另一方面來說也是個不錯的功能
(如果可以做到區域內再划分區域的話,就像Town 插件)
所以我想開發者可不可以在config中加入一項
是否允許Claim地重疊?

**Comment by fihgus** [comment]
已阅.

**Comment by fihgus** [comment]
重叠区域会导致读取一个值而获得两个结果, 会造成迷惑性的结果.
