### ISSUE TITLE
I do not understand the explanation of "how to set the permissions . "

### ISSUE THREAD

**Issue by FranGamer1892** [fihgus/Slash#35]
I did not understand how to write permissions on permisson.txt. I have to write a permission in the group 'players'. /claim is that permission . But I could not write that players can do /claim { ID} (claim an area to build their own home).I've already had a server bukkit. But in bukkit the types of permissions are different.Also, if I do not want players to make / slash or / share , what should I do to remove that permission? Sorry if bad english, I speak Spanish. Thank you. If you not understand I say this in spanish.

**Comment by FranGamer1892** [comment]
I don t understand, sorry D:

**Comment by fihgus** [comment]
check the new tut video

**Comment by FranGamer1892** [comment]
I'm in 1.7.2  and i don't understand japanese or chinese

**Comment by fihgus** [comment]
1.7.2 is no longer support

--- Original Message ---
